### ISSUE TITLE
chyba strankovani podmnozin skupiny

### ISSUE THREAD

**Issue by martenson** [SmallhillCZ/Supervizor#10]
pokud na strance: http://data.mfcr.cz/supervizor/skupina/nakup vyberu v levem menu nejakou podmnozinu skupiny dat (napriklad 5177 - Nákup uměleckých předmětů) a pote se pokusim dostat na jeji druhou stranku zobrazi se mi druha stranka _nefiltrovanych_ dat dane skupiny (tedy jako bych nemel vybranou podmnozinu). Situace zachycena zde:
![screenshot 2016-04-12 23 18 39](https://cloud.githubusercontent.com/assets/1814954/14481880/0914c854-0105-11e6-850d-0d0b210e9658.png)
Na pozadovanou stranku se dostanu opetovnym kliknutim na podmnozinu v levem menu.

**Comment by Salamek** [comment]
> Bug
> Confirmed
