### ISSUE TITLE
zmena licence na opravdu svobodnou

### ISSUE THREAD

**Issue by martenson** [SmallhillCZ/Supervizor#15]
GNU GPL neni povazovana za svobodnou licenci, protoze jakykoliv derivat musi byt vydan pod stejnou licenci.

Bylo by mozne zmenit licenci napriklad na MIT, Apache nebo Academic Free Licence? 
- http://www.linuxjournal.com/article/5935
- https://noordering.wordpress.com/2009/01/20/why-the-gpl-is-not-free/
- http://www.charvolant.org/~doug/gpl/gpl.pdf

**Comment by martenson** [comment]
@Salamek proc ta nechut?

edit: zaviram, ale presto bych rad otevrel debatu

**Comment by Salamek** [comment]
@martenson Muj osobni nazor je takovy ze MIT/BSD/WTFPL etc. se hodi na knihovny kde je vysoka sance ze kdokoliv kdo bude knihovnu pouzivat at uz komercne ci v jinem OSS bude zmeny/bugy posilat do mainstreamu(je mnohem jednodusi udrzba nez si drzet vlastni fork/privatni verzi) a zaroven jej nebude omezovat licence. 
Ale na cele samostatne projekty (funkcni celky) nic takoveho neplati... nekdo muze cely projekt vzit, prejmenovat, zacit vyvijet a prodavat jako komercni produkt, kde originalni tvurci maji prd (at uz vyvojove nebo financne) GNU GPL ~zarucuje ze originalni tvurce aplikace (a kdokoliv jiny) muze mit alespon pristup k vyvoji onoho forku (Zarucuje budouci svobodu).

http://www.linuxjournal.com/article/5935 tady ten clovek breci nad tim ze komercni firmy jsou chudaci protoze jim GPL zakazuje vzit OSS SW a prodavat jej jak se jim zlibi bez vydani zmen... takova by totiz byla realita kdyby napr M$ postavil svuj mailserver na OSS projektu jak je uvedeno v odkaze (coz klidne tehdy mohli ale to je na jinou diskuzi) tak by rozkopali protokol, nevydali dokumentaci a ani by nevydali patche, M$ by jen usetril na vyvoji a testovani a OSS komunita by ostrouhala, OSS vyvojari daneho mailserveru by pak v kreci plakali u gigantickeho billboardu "New super secure & fast M$ Exchange! only for XX XXX/m buy NOW!!!"

Pokud nekdo nechce splnit podminky GNU GPL (tzn chce projekt pouze pro sve vlastni prilepseni) a chce pouzit dany SW tak stale muze pozadat originalniho autora o prelicencovani nebo o komercni licenci...

**Comment by martenson** [comment]
@Salamek Diky za vysvetleni pozice, rozumim, nesouhlasim vsak se zavery. Pokud prijde zitra magistrat mesta Brna s tim, ze by radi upravili a pouzili tuhle aplikaci pro rozpocet, tak to nebudou moci udelat dokud nesplni podminky 'nakazlivosti', coz muze byt administrativni zatez nebo stopka. Toto omezeni mi prijde zbytecne a v tomto pripade nepotrebne.

**Comment by Salamek** [comment]
@martenson no to je muj osobni nazor... a zrovna v tebou uvedenem priklade nejak nevidim duvod proc by mela GPL licence magistratu mesta Brna vadit ? (Nejak si nedokazi predstavit situaci kdy by doslo na nejaky opravdovy licencni konflikt) Nejaky konkretni priklad problemu ?

**Comment by SmallhillCZ** [comment]
My jsme to tu řešili, v podstatě argumenty pro GPL byly:
- Nemyslíme si, že by to někdo potřeboval použít komerčně a zároveň měl důvod nezveřejňovat změněné zdrojáky. Aplikace není modul/knihovna pro použití v jiném software a jako taková je na jednu věc, tj. umí zobrazovat rozpočet do bublin, takže využití hlavně organizacemi státní správy a územními samosprávními celky.
- Právní oddělení nám navrhlo GPL
- Byť si myslím, že by se to na 99,9% nestalo, tak by bylo mediálně dost nevhodné, kdyby to někdo vylepšil a začal prodávat nebo dávat s reklamou aniž bychom z toho něco měli (tím myslím ty kódy ne peníze), což ne že bych zas tak lpěl na mediálním obrazu, ale mohlo by to negativně ovlivnit podobné snahy (open source, open data, ...) do budoucna.

Každopádně pokud se najde nějaký dobrý důvod proč licenci změnit, nemáme s tím problém.
