### ISSUE TITLE
Mysql driver

### ISSUE THREAD

**Issue by Kedrigern** [SmallhillCZ/Supervizor#16]
Zdravím,

zkusil jsem si aplikaci spustit dle návodu v readme. A narazil jsem na drobný problém. 

V `config.local.neon` je potřeba mít `driver: 'mysql'` a zároveň v `extension.doctrine.neon` je třeba mít `driver: 'pdo_mysql'` namísto `driver: %database.driver%` (což se přeloží na `mysql`).

V Nette již 2 roky nepracuji a Doctrine neznám. Čili mi možná uniká něco zjevného, anebo je to opravdu chyba. Mohl by se k tomu vyjádřit někdo zkušenější?

Verze Supervizor: c214df728b0c871c8339d4c849a24f6eec8cc44a
Verze PHP:  PHP 5.6.22 
OS: Fedora 23 s SELinux

**Comment by castamir** [comment]
Chápu to správně, že ti to funguje s nastavením `extension.doctrine.neon` s řádkem `driver: 'pdo_mysql'`?

Pravděpodobně nemáš nainstalované mysql extension nebo ho máš v php.ini zakomentované. To však nevadí. I s pdo_mysql můžeš pracovat.

Správné nastavení by mělo být

```
# extension.doctrine.neon
driver: %database.driver%
```

```
# config.local.neon
driver: 'pdo_mysql'
```

Vyzkoušej to prosím.

Nastavení přístupových údajů je úmyslně v samostaném souboru, který se neverzuje. Na produkčním ani jiném prostředí nechceme používat přihlašovací údaje z jiných strojů. Tvá úprava tohle částečně porušuje. Ikdyž může být na tvém stroji daná úprava funkční, nemusí již být přenositelná (na jiném stroji můžeš chtít použít jiný ovladač).

---

v `config.local.neon` by mělo být jedno, jaký typ databáze nebo driveru zvolíš. Já jsem to testoval na mysqli a sqlsrv.

**Comment by Kedrigern** [comment]
Ano, chápeš to správně. Též mě to překvapilo, není mou snahou mít nepřhledné configy. 

Pokud mám v obou souborech jen `driver: mysql` (resp. z jednoho se to propíše do druhého), tak to vyhodí exception:

```
Doctrine\DBAL\DBALException
The given 'driver' mysql is unknown, Doctrine currently supports only the following drivers: pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, drizzle_pdo_mysql, sqlanywhere, sqlsrv
```

PHPinfo píše:

```
API Extensions  mysql,mysqli,pdo_mysql 
```

Doctrine využívá nějaký speciální driver? Mě se zdá, že vše mám nainstalované správně. Resp. nevím, co přesněji hledat.

**Comment by castamir** [comment]
Funguje ti v `config.local.neon` tohle: `driver: 'pdo_mysql'` popř. `driver: 'mysqli'` (všimni si toho i na konci)? `mysql` driver je totiž zastaralý, v php7 už dokonce vůbec není.

Každopádně to chybové hlášení je docela výmluvné - doctrine už starý driver `mysql` nepodporuje.

Mimochodem, já jsem v doctrine taky zelenáč. Když mám tu možnost, sahám po jiném, odlehčenějším řešení...

**Comment by Salamek** [comment]
@Kedrigern @castamir v https://raw.githubusercontent.com/SmallhillCZ/Supervizor/master/app/config/config.local.neon.example je uveden spatny driver, spravne by tam melo by pdo_mysql, tak je to trochu matouci... je to moje chyba pri vyvoji jsem ten example config napsal z hlavy a pak pri testovani to opravil jen v "neexample" verzi (ktera samozrejme na gitu neni), mysql driver je obsolete a nemel by se pouzivat

Fixed in #17

**Comment by Kedrigern** [comment]
Ano, to bylo ono. Velmi děkuji za opravu.
