### ISSUE TITLE
Zalozeni GH profilu/organizace MF CR

### ISSUE THREAD

**Issue by martenson** [SmallhillCZ/Supervizor#9]
Mohl by se prosim tento repositar a jakekoliv dalsi, ktere MF spravuje ci zverejnuje prenest pod ucet MF a nikoliv pod soukromy ucet @SmallhillCZ ?

Zverejneni je skvela vec a jak vidno na https://github.com/SmallhillCZ/Supervizor/pulls (zatim tedy hlavne @spaze) komunita se zacina tvorit. Byla by skoda aby se veskera prace pojila k soukromemu namespace, ktere muze kdykoliv zmizet.

edit: GH nabizi bezproblemovy presun repa vcetne redirektu, PR a cehokoliv dalsiho

**Comment by SmallhillCZ** [comment]
Budeme muset probrat s právním a tiskovým oddělením...

**Comment by SmallhillCZ** [comment]
Hotovo.

**Comment by martenson** [comment]
bezvadne! diky @SmallhillCZ
